### ISSUE TITLE
full HTML5 support

### ISSUE THREAD

**Issue by remixer-dec** [mkoterle/twitchls#1]
Can you please add html5 player to not-HLS-comatible browsers? Player url: http://player.twitch.tv/?channel={channel_name}&html5=true

**Comment by mkoterle** [comment]
Sadly only the player controls are in HTML5. The streaming part is still using Flash on non HLS compatible browsers.

I can update the views to use the player.twitch.tv instead of the current one. I can't find the html5 flag for the player in the official [documentation located here](https://github.com/justintv/Twitch-API/blob/master/embed-video.md). 
Do you have any other source of information where this flag is mentioned? Thanks.

**Comment by remixer-dec** [comment]
I just disabled flash player in firefox and randomly added html5=true (this flag was in youtube few years ago), and it worked! Probably its a beta feature, because VODs are not working, only live streams.

**Comment by mkoterle** [comment]
Oh wow. Interesting find. Adding this.

Thanks!
